name: CI Pipeline

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  COMMON_REPO_URL: https://github.com/lets-go-programming-contest/lets-go-programming-ci-common.git

jobs:
  sanity-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone utils repo
        uses: actions/checkout@v4
        with:
          repository: "lets-go-programming-contest/lets-go-programming-ci-utils"
          path: ".ci_utils"
      
      - name: "ls la"
        run: ls -la .ci_utils

      - name: Run sanity files checks
        run: make -f .ci_utils/Makefile docker-sanity-student
