name: CI Pipeline

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_CONTAINER_NAME: andrianovartemii/lgp-ci-utils
  DOCKER_CONTAINER_TAG: latest
  TEST_DIR_UTILS: .ci_utils
  UTILS_REPO_URL: lets-go-programming-contest/lets-go-programming-ci-utils
  TEST_DIR_COMMON: .ci_common
  COMMON_REPO_URL: lets-go-programming-contest/lets-go-programming-ci-common

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout utils files
        uses: actions/checkout@v4
        with:
          repository:  ${{ env.UTILS_REPO_URL }}
          path: ${{ env.TEST_DIR_UTILS }}

      - name: Checkout common files
        uses: actions/checkout@v4
        with:
          repository:  ${{ env.COMMON_REPO_URL }}
          path: ${{ env.TEST_DIR_COMMON }}

      - name: "Pull enviroment container"
        run: docker pull ${DOCKER_CONTAINER_NAME}:${DOCKER_CONTAINER_TAG}

      - name: "Validate files"
        run: make -f ${TEST_DIR_UTILS}/Makefile docker-sanity-files

      - name: "Valide student"
        run: make -f ${TEST_DIR_UTILS}/Makefile docker-sanity-student

      - name: "Valide tasks"
        run: make -f ${TEST_DIR_UTILS}/Makefile docker-sanity-tasks

